[build]
builder = "NIXPACKS"
buildCommand = "cd back && npm install --omit=dev && npm run build"

[deploy]
startCommand = "cd back && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10